### ISSUE TITLE
Problem with annotation file for proteome discoverer

### ISSUE THREAD

**Issue by MAmaldacker** [Vitek-Lab/MSstatsTMT#63]
Hello,

I currently want to run the MSStatsTMT pipeline on the Galaxy Server and this has worked in the past for MaxQuant data. Now, I want to process the same data set with Proteome Discoverer and MSStatsTMT. While using MSStatsTMT implemented on the  Galaxy server,  I always faced the same error messages: " _** Please check the annotation file. The channel name must be matched with that in input data_." Following the documentation, I named the channels in the annotation file (126, ..., 131) according to the columns in the PSM file (Abundance: 126, ..., Abundance 131). Afterwards, I tried some  different combinations but none of them has worked yet, thus I would be really thankful for any advice.

I currently use the PSM output from a TMT6plex data set processed with Proteome discoverer 2.5.0. on the Galaxy server. Attached to this message, you can have a look on a shortened PSM.txt file and the annotation file.

Thank you for your help!
M. Maldacker

[TMT10_PSMs_short.txt](https://github.com/Vitek-Lab/MSstatsTMT/files/8948947/TMT10_PSMs_short.txt)
[Diff_Row_PD_annotation.txt](https://github.com/Vitek-Lab/MSstatsTMT/files/8948948/Diff_Row_PD_annotation.txt)

**Comment by MAmaldacker** [comment]
Hello @npinter,
thank you for the fast feedback! I ran the tool again with your suggested changes (e.g. channel.1 instead of 126). No I get the following error: 

_"Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 1476 did not have 61 elements
Calls: read.table -> scan"_

I have not indication that the PSM file is corrupted. Do you have any further suggestions? 

Greetings
Maximilian

**Comment by npinter** [comment]
The error was raised since the underlying R script on Galaxy does not like `"` and `'`. We need to change the wrapper/R script here slightly... I was able to load the PSM file locally after removing both characters (search and replace). Consider removing empty lines as well, you have ~100k of them in that file. A regular expression to catch those is `\t{60}\n`. Just search and replace with nothing to remove them with any modern text editor (Windows Notepad++, Ubuntu GNU emacs). 

However, the script fails with another error:
`Error in PDtoMSstatsTMTFormat(PSM.pd, annotation = annotation.pd, which.proteinid = "Protein.Accessions",  (test_msstatstmt.R#9): Please check the annotation file. 'Run' must be matched with 'Spectrum.File'. `

since your PSM file only contains entries for just one of the three raw files in your annotation matrix.

Hope this helps :)

Best
Niko

**Comment by npinter** [comment]
![grafik](https://user-images.githubusercontent.com/34959927/175836076-542d1ea6-50c8-4929-8232-9376d85df702.png)
2 of 3 samples names in your annotation file have an additional whitespace. After removing those it worked for me :)

**Comment by MAmaldacker** [comment]
Hey, 

I deleted the spaces in the annotation file and also changed the channels back to 126 to 131. I tried this with the orginial PSM file, with the one that didn't contain any `"` or `'` and the shortened one I provided here. I still received the error message:

```
Error in .mergeAnnotation(input, annotation) : 
  ** Please check the annotation file. The channel name must be matched with that in input data.
```
Do you have any further advice? 

Best
Maximilian

**Comment by npinter** [comment]
Sorry for the late response.. and sorry, I only tested your inputs with a R script generated by a local Galaxy test instance.. The R script (w/o Galaxy) worked since I used an older MSstats/MSstatsTMT  version than Galaxy uses.

However, I got it working with the inputs you provided by switching this parameter to "No"/False in Galaxy:
![grafik](https://user-images.githubusercontent.com/34959927/177520983-169a9254-d974-4895-b756-c085b2351687.png)

Best
Niko

**Comment by MAmaldacker** [comment]
Hello Niko,

now it worked finally. I tried it with R before but I did not figure out what the main reason was for that. So i switched on the galaxy tool. And indeed, I used pandas in order to trimm the input files. 

Now that it worked, thank you so much for the support and the time you have invested!

Best,
Maximilian
